/**
 * Files the reference promises but does not ship.
 *
 * `.claude/README.md` documents nested CLAUDE.md files for api/, mobile/ and
 * web/*, but only the web ones exist (and those are one-line `@AGENTS.md`
 * stubs that Next.js regenerates). The mobile one is load-bearing: it is the
 * only documented route by which the edge-to-edge safe-area rule reaches
 * Claude, since that rule is deliberately excluded from the always-apply set.
 */

export function apiClaudeMd(cfg) {
  return `# api/ — ${cfg.displayName} API

Hono on Node, ESM with NodeNext resolution. Not Next.js: \`next\` appears only
as a transitive dependency of the shared packages.

## Commands

\`\`\`bash
pnpm dev          # tsx, hot reload
pnpm build        # tsc
pnpm test         # vitest
pnpm lint         # biome
pnpm type-check   # tsc --noEmit
\`\`\`

Run a single test: \`pnpm exec vitest run src/lib/apiError.test.ts\`

## Layout

- \`src/app.ts\` — \`createApp()\`, the Hono app and zod env schema. Middleware plugs in here.
- \`src/server.ts\` — entry point: serve + database connect.
- \`src/v1/\` — versioned route tree.
- \`src/lib/\` — cross-cutting helpers (errors, rate limiting, health, redis).
- \`src/jobs/\` — BullMQ workers. \`src/realtime/\` — Socket.IO. \`src/logAgent/\` — log shipping.

## Conventions

- Errors go through \`apiError(code, message)\` / \`throwApiError\`, never bare \`Response\`.
  Codes are the stable contract; HTTP status is derived from them.
- Every route validates input with zod.
- Tests are colocated as \`*.test.ts\`.
`;
}

export function mobileClaudeMd(cfg) {
  return `# mobile/ — ${cfg.displayName} app

Expo / React Native with expo-router. iOS and Android ship from this one codebase.

## Commands

\`\`\`bash
pnpm start          # Metro on the LAN
pnpm ios            # native debug build (simulator)
pnpm android
pnpm typecheck      # tsc --noEmit
pnpm test           # vitest
pnpm check:locales  # assert locale bundles are in parity
\`\`\`

Run a single test: \`pnpm exec vitest run lib/i18n/normalizePreferredLanguage.test.ts\`

## Safe area (Android edge-to-edge)

The app runs edge-to-edge, so the system bars overlap the content area.

- \`SafeAreaProvider\` wraps the tree in \`app/_layout.tsx\`.
- Any bottom-anchored surface derives its padding from \`useSafeAreaInsets().bottom\`.
  Never hard-code a bottom offset.
- Tab layouts use the shared tab-chrome screen options rather than per-screen padding.
- Cover both cases in tests: a non-zero inset and a zero inset (a device with no
  navigation bar must not gain dead space).

## Conventions

- Icons come from \`@expo/vector-icons\`.
- Colors are semantic and theme-aware; no hard-coded hex values in components.
- Locale bundles live in \`locales/*.json\` and must stay key-identical — \`check:locales\` enforces it.
- Native projects (\`ios/\`, \`android/\`) are generated by \`expo prebuild\` and are not committed.
  Configure them through \`app.config.ts\` and the config plugins in \`plugins/\`.
`;
}

export function sharedPackagesDoc(cfg) {
  if (cfg.wyscanMode === "standalone") {
    return `# Shared packages

This project was scaffolded in **standalone** mode: it installs from public npm
alone, with no dependency on a sibling checkout.

## What the stubs are

\`packages/stubs/\` contains minimal local stand-ins for the shared packages:

| Package | Provides |
|---|---|
| \`${cfg.npmScope}/core-api\` | \`logger\`, \`AppError\` / \`handleError\` / \`Errors\`, \`checkRateLimit\`, \`stripHtmlTags\`, \`initWebSocket\` |
| \`${cfg.npmScope}/auth-api\` | \`verifyAccessToken\` |
| \`${cfg.npmScope}/notify-api\` | \`initializeFirebase\`, \`isFirebaseInitialized\`, \`sendPush\` |
| \`${cfg.npmScope}/core-react-native\` | \`createI18n\` |

They are real implementations, not throwing placeholders, so the app boots and
the test suite passes. They are deliberately simple — for example the rate
limiter is an in-memory sliding window, which is correct for a single process
and wrong across replicas.

## Adopting the real packages

Import specifiers in application code are identical to the real packages, so
adoption is a dependency swap, not a code change:

1. Point the deps at the real source — either a sibling checkout
   (\`file:../../${cfg.ecosystemDir}/Packages/packages/...\`) or your registry.
2. Delete \`packages/stubs/\`.
3. Reinstall.

Anything you build on top of a stub keeps working, provided you did not rely on
behaviour the real package does not have.
`;
  }

  if (cfg.wyscanMode === "registry") {
    return `# Shared packages

This project resolves shared packages from a scoped registry (\`${cfg.npmScope}\`).

## Setup

1. Create a token with \`read:packages\`.
2. Export it as \`NPM_TOKEN\`, or add it to \`docker/build.env\` for image builds.
3. \`pnpm install\` in each workspace.

## Before your first real install

Version ranges were set to a placeholder at scaffold time. Pin them to the
versions you actually publish, then commit the resulting lockfiles — they were
deliberately omitted from the scaffold because they would have been stale.
`;
  }

  return `# Shared packages

This project consumes shared packages from a sibling checkout at
\`../${cfg.ecosystemDir}\` via pnpm \`file:\` links.

## Setup

\`\`\`bash
make wyscan-dev-setup      # clone the sibling repos
make design-system-setup   # optional: check out a design-system branch
\`\`\`

Because pnpm's \`file:\` copy omits gitignored build output, the API dev scripts
rebuild each package's \`dist/\` before starting. Metro bypasses the copy entirely
and bundles the live sources.

If the sibling checkout lives elsewhere, set \`WYSCAN_PACKAGES\` (Make) or the
matching env var (see \`api/.env.example\`).
`;
}
