#!/usr/bin/env node
/**
 * Regenerate docs/features/README.md — the feature index over active
 * (docs/features/NNNN-slug/) and archived (docs/features/archive/NNNN-slug/)
 * feature docs. Deterministic: rerunning without changes produces no diff.
 *
 * Usage: node scripts/features-index.mjs   (or: make features-index)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FEATURES_DIR = path.join(ROOT, "docs", "features");
const ARCHIVE_DIR = path.join(FEATURES_DIR, "archive");
const FEAT_RE = /^\d{4}-[a-z0-9][a-z0-9-]*$/;

function listDirs(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);
}

const active = listDirs(FEATURES_DIR).filter((n) => n !== "archive");
const archived = listDirs(ARCHIVE_DIR);

const invalid = [...active, ...archived].filter((n) => !FEAT_RE.test(n));
if (invalid.length > 0) {
  console.error(`Feature directories not matching NNNN-slug: ${invalid.join(", ")}`);
  process.exit(1);
}

const TITLE_PREFIX_RE = /^(feature spec|implementation plan)\s*:\s*(\d{4}\s*[—-]\s*)?/i;

function titleFor(dirAbs, slug) {
  for (const file of ["spec.md", "implementation-plan.md"]) {
    const p = path.join(dirAbs, file);
    if (!fs.existsSync(p)) continue;
    const m = fs.readFileSync(p, "utf8").match(/^#\s+(.+)$/m);
    if (m) return m[1].trim().replace(TITLE_PREFIX_RE, "").replace(/\|/g, "\\|");
  }
  return slug.replace(/^\d{4}-/, "").replace(/-/g, " ");
}

const idCounts = new Map();
for (const name of [...active, ...archived]) {
  const id = name.slice(0, 4);
  idCounts.set(id, (idCounts.get(id) ?? 0) + 1);
}

function rows(names, baseAbs, linkPrefix) {
  return [...names]
    .sort()
    .map((name) => {
      const id = name.slice(0, 4);
      const dirAbs = path.join(baseAbs, name);
      const dup = idCounts.get(id) > 1 ? " *(duplicate ID)*" : "";
      const title = titleFor(dirAbs, name) + dup;
      const cell = (file) =>
        fs.existsSync(path.join(dirAbs, file)) ? `[${file.replace(".md", "")}](${linkPrefix}${name}/${file})` : "—";
      return `| ${id} | ${title} | ${cell("spec.md")} | ${cell("implementation-plan.md")} |`;
    });
}

const TABLE_HEADER = ["| ID | Feature | Spec | Plan |", "| --- | --- | --- | --- |"];

const out = [
  "# Feature Index",
  "",
  "Generated by `scripts/features-index.mjs` (`make features-index`) — do not edit by hand.",
  "",
  "IDs are global and monotonic across the root and `archive/`: the next feature ID is",
  "max(both locations) + 1 — archiving never frees an ID. Old features move to the flat",
  "`archive/` directory via `make features-archive UP_TO=NNNN` (see `.claude/rules/references.md`).",
  "",
  `## Active (${active.length})`,
  "",
  ...TABLE_HEADER,
  ...rows(active, FEATURES_DIR, ""),
  "",
  `## Archived (${archived.length})`,
  "",
  ...TABLE_HEADER,
  ...rows(archived, ARCHIVE_DIR, "archive/"),
  "",
];

fs.writeFileSync(path.join(FEATURES_DIR, "README.md"), out.join("\n"));
console.log(`docs/features/README.md regenerated: ${active.length} active, ${archived.length} archived.`);
